### ISSUE TITLE
Video file is not sent

### ISSUE THREAD

**Issue by muzafferkarakan** [tobagin/karere#49]
When I want to send a video via Karere, only the **image** type is selected and it is not possible to send the **mp4** file.

**Comment by tobagin** [comment]
will look into it! it maybe be related to the missing codec

**Comment by muzafferkarakan** [comment]
> will look into it! it maybe be related to the missing codec
Video file does not appear when selection is made.
Thank you for your interest.

<img width="483" height="405" alt="Image" src="https://github.com/user-attachments/assets/b884acd7-707d-4d60-af6d-ff8c511f7840" />
<img width="1477" height="329" alt="Image" src="https://github.com/user-attachments/assets/65933b13-0017-4a6f-bc5f-defa3e8ecab8" />

**Comment by tobagin** [comment]
I just pushed a new build to flathub and it should solve this issue

**Comment by tobagin** [comment]
This seems to be related to WebKitGTK, I logged in on my end using GNOME Web and I have the same issue to send videos and both use the same tech. Since this is related to WebKitGTK and there isn't another option to be used with GTK/LibAdwaita unfortunately there is not much it can be done at this state. I will document the limitation on the READMe.md and close this issue for now.

**Comment by muzafferkarakan** [comment]
> This seems to be related to WebKitGTK, I logged in on my end using GNOME Web and I have the same issue to send videos and both use the same tech. Since this is related to WebKitGTK and there isn't another option to be used with GTK/LibAdwaita unfortunately there is not much it can be done at this state. I will document the limitation on the READMe.md and close this issue for now.

Unfortunately. I updated and checked and still the same problem persists. Thank you for your interest.

**Comment by tobagin** [comment]
Unfortunately it seems that this is related to one of the underlying technologies used by Karere and at this stage there is nothing I can do to solve it.
